title: Computational and Inferential Thinking
author: Ani Adhikari and John DeNero and David Wagner
email: ''
logo: "images/logo.png"
exclude_patterns: ["README.md"]

execute:
  execute_notebooks         : 'off'
  timeout                   : 600

html:
  favicon                   : "images/logo.png"
  navbar_number_sections    : false
  home_page_in_navbar       : false
  baseurl                   : "https://ccsf-math-108.github.io/textbook"
  use_repository_button     : false
  use_edit_page_button      : false
  use_issues_button         : false

launch_buttons:
  jupyterhub_url            : https://ccsf.cloudbank.2i2c.cloud/
  notebook_interface        : classic

repository:
  url                       : https://github.com/ccsf-math-108/textbook
  branch                    : main

sphinx:
  config:
    html_extra_path: ['assets']
    html_context:
      default_mode: "light"